contact_links:
  - name: Feedback & Feature Requests
    url: https://github.com/HeccBot/HeccBot/discussions/new/choose
    about: Have ideas for TwiLite? Post it in our Discussions tab!
  - name: Support Server
    url: https://discord.gg/BdXQjkADgd
    about: Need real-time help & support? Head on over to our Support Server on Discord.
  - name: Add App to Server
    url: https://discord.com/api/oauth2/authorize?client_id=784058687412633601&permissions=274878221312&scope=applications.commands%20bot
    about: Want to add TwiLite to your own Server? Use this link here!
  - name: Add App to Account
    url: https://discord.com/api/oauth2/authorize?client_id=784058687412633601&scope=applications.commands&integration_type=1
    about: Want to add TwiLite to your account? Use this link here!
